stages:
  - lint
  - test
  - build

lint-src:
  stage: lint
  image: docker.io/golangci/golangci-lint:v2.3.0
  script:
    - golangci-lint run

test-src:
  stage: test
  image: docker.io/library/golang:1.21
  before_script:
    - make
  script:
    - make test


.build-image:
  image: quay.io/buildah/stable:latest
  stage: build
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
  before_script:
    - if [ ! -z "${DOCKER_REGISTRY_USER}" ] && [ ! -z "${DOCKER_REGISTRY_PASSWORD}" ] ;
      then
        buildah login -u "${DOCKER_REGISTRY_USER}" -p "${DOCKER_REGISTRY_PASSWORD}" "${DOCKER_REGISTRY}" ;
      fi
  script:
    # Build container
    - echo "Building ${DOCKER_REGISTRY}/${REGISTRY_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}"
    - buildah bud --storage-driver=${STORAGE_DRIVER} -t ${DOCKER_REGISTRY}/${REGISTRY_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG} -f Containerfile .
    - buildah tag ${DOCKER_REGISTRY}/${REGISTRY_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG} ${DOCKER_REGISTRY}/${REGISTRY_PATH}/${CI_PROJECT_NAME}:latest
    - buildah push --storage-driver=${STORAGE_DRIVER} ${DOCKER_REGISTRY}/${REGISTRY_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}
    - buildah push --storage-driver=${STORAGE_DRIVER} ${DOCKER_REGISTRY}/${REGISTRY_PATH}/${CI_PROJECT_NAME}:latest

build-image-arm64v8:
  variables:
    REGISTRY_PATH: arm64v8
  extends:
    - .build-image
  tags:
    - arm64v8
    
build-image-x86_64:
  variables:
    REGISTRY_PATH: x86_64
  extends:
    - .build-image
  tags:
    - x86_64
